import { PDFDocument } from "pdf-lib";
import crypto from "crypto";

export type EsignAuditRecord = {
  auditId: string;
  documentId: string;
  inviteId: string;
  senderEmail: string;
  recipientEmail: string;
  senderUid?: string;
  recipientUid?: string;
  createdAt?: any;
  senderSignedAt?: any;
  recipientSignedAt: any;
  completedAt: any;
  senderIp?: string;
  recipientIp?: string;
  signedPdfUrl?: string;
  signedPdfPath?: string;
  hash: string;
  verificationId: string;
};

type BuildAuditArgs = {
  documentId: string;
  inviteId: string;
  senderEmail: string;
  recipientEmail: string;
  senderUid?: string;
  recipientUid?: string;
  createdAt?: any;
  senderSignedAt?: any;
  recipientSignedAt: any;
  completedAt: any;
  senderIp?: string;
  recipientIp?: string;
  signedPdfUrl?: string;
  signedPdfPath?: string;
};

export function buildAuditRecord(args: BuildAuditArgs): EsignAuditRecord {
  const auditId =
    typeof crypto.randomUUID === "function"
      ? crypto.randomUUID()
      : `${Date.now()}-${Math.random().toString(16).slice(2)}`;

  const verificationId = auditId;

  return {
    auditId,
    documentId: args.documentId,
    inviteId: args.inviteId,
    senderEmail: args.senderEmail,
    recipientEmail: args.recipientEmail,
    senderUid: args.senderUid,
    recipientUid: args.recipientUid,
    createdAt: args.createdAt,
    senderSignedAt: args.senderSignedAt,
    recipientSignedAt: args.recipientSignedAt,
    completedAt: args.completedAt,
    senderIp: args.senderIp,
    recipientIp: args.recipientIp,
    signedPdfUrl: args.signedPdfUrl,
    signedPdfPath: args.signedPdfPath,
    // hash is populated by the caller once the final PDF bytes are available
    hash: "",
    verificationId,
  };
}

export async function appendAuditCertificatePage(
  signedPdfBytes: Uint8Array | Buffer,
  audit: EsignAuditRecord
): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.load(
    signedPdfBytes instanceof Uint8Array ? signedPdfBytes : new Uint8Array(signedPdfBytes)
  );

  const page = pdfDoc.addPage();
  const { width, height } = page.getSize();

  const margin = 50;
  let y = height - margin;

  const titleFontSize = 20;
  const labelFontSize = 11;
  const valueFontSize = 12;
  const lineGap = 18;

  page.drawText("Studiosis Lab Audit Certificate", {
    x: margin,
    y,
    size: titleFontSize,
  });
  y -= lineGap * 2;

  const drawPair = (label: string, value: string | undefined | null) => {
    if (!value) return;
    page.drawText(`${label}:`, {
      x: margin,
      y,
      size: labelFontSize,
    });
    page.drawText(value, {
      x: margin + 140,
      y,
      size: valueFontSize,
    });
    y -= lineGap;
  };

  drawPair("Document ID", audit.documentId);
  drawPair("Invite ID", audit.inviteId);
  drawPair("Sender Email", audit.senderEmail);
  drawPair("Recipient Email", audit.recipientEmail);
  drawPair(
    "Completed At",
    audit.completedAt instanceof Date
      ? audit.completedAt.toISOString()
      : String(audit.completedAt ?? "")
  );
  drawPair("Signer IP", audit.recipientIp ?? "");
  drawPair("Verification ID", audit.verificationId);

  y -= lineGap;

  page.drawText("Generated by Studiosis Lab Secure E-Signature", {
    x: margin,
    y,
    size: 10,
  });

  return pdfDoc.save();
}

