import type { CorpusAnalysisSummary } from "./types.js";

/**
 * Empirical analysis of all published StudiosisLab resume templates (read-only corpus study).
 * Source: templates.manifest.json + src/data/template-json/*.json
 * Do NOT modify product templates — analysis for knowledge only.
 */
export const TEMPLATE_CORPUS_ANALYSIS: CorpusAnalysisSummary = {
  analyzed_at: "2026-07-06",
  published_template_count: 79,
  canvas_dimensions: {
    "794x1123_A4": 72,
    "2480x3508_legacy": 2,
  },
  fabric_versioned_count: 72,
  legacy_format_count: 7,
  object_type_distribution: {
    textbox: 1787,
    rect: 170,
    line: 252,
    group: 151,
    image: 55,
    circle: 57,
    triangle: 5,
  },
  font_families_observed: [
    "Times New Roman",
    "Arimo",
    "Inter",
    "Montserrat",
    "Roboto",
    "DM Sans",
    "Google Sans",
    "Heebo",
    "Poppins",
    "Open Sans",
    "Archivo",
    "Roboto Slab",
    "Lato",
    "Nunito",
    "Work Sans",
    "Lora",
    "Playfair Display",
    "Noto Serif",
  ],
  font_size_range: { min: 10.487, max: 64, average: 17 },
  negative_positioning_objects: 92,
  image_object_count: 55,
  group_object_count: 151,
  category_distribution: {
    business: 8,
    "business-management": 9,
    "customer-service-administration": 10,
    "healthcare-medical": 9,
    "finance-accounting": 7,
    "sales-marketing-advertising": 7,
    "it-software": 8,
    it: 4,
    "creative-designing": 5,
    creative: 1,
    "hospitality-travel": 4,
    "student-entry-level": 2,
    engineering: 1,
    "logistics-operations": 1,
    healthcare: 1,
    "sales-marketing": 1,
    "others-student-entry-level": 1,
  },
  section_keyword_frequency: {
    experience: 116,
    skills: 99,
    education: 69,
    project: 63,
    summary: 38,
    profile: 24,
    language: 23,
    certification: 23,
    contact: 20,
    reference: 17,
    objective: 8,
    award: 6,
  },
  improvement_gaps: [
    "92 Fabric objects use negative left/top — risks non-linear ATS reading order",
    "55 image objects — text-in-image and decorative graphics reduce ATS parse reliability",
    "151 grouped objects — nested groups can scramble export/parse order",
    "7 legacy JSON files lack Fabric version metadata — inconsistent load behavior",
    "2 templates use 2480×3508 canvas instead of standard A4 794×1123",
    "Heavy use of decorative rects/lines (422) — ensure section text remains plain and left-aligned",
    "Web fonts (Montserrat, Poppins, Playfair) used widely — provide ATS-safe font fallback tier",
    "charSpacing up to 210 observed — extreme letter-spacing hurts readability and OCR",
  ],
};

export const FABRIC_JSON_STRUCTURE = {
  required_root_fields: ["objects"],
  recommended_root_fields: ["version", "width", "height", "background"],
  standard_canvas: { width: 794, height: 1123, page_size: "A4" },
  legacy_canvas: { width: 2480, height: 3508 },
  supported_object_types: ["Rect", "Textbox", "Line", "Group", "Image", "Circle", "Triangle"],
  positioning_rules: [
    "Page background rect at (0,0) with full canvas dimensions",
    "Content safe area: left ≥ 40px, top ≥ 40px, right margin ≥ 40px",
    "Avoid negative left/top except full-bleed backgrounds locked non-selectable",
    "Reading order follows ascending top, then ascending left",
  ],
  export_behavior: {
    thumbnail_multiplier: 0.25,
    pdf_export_multiplier: 2,
    format: "PNG embedded in jsPDF portrait pages",
    background: "#ffffff",
  },
} as const;
