/**
 * ComparisonScorecard — 18 comparison dimensions (Mock vs Real later).
 * Mock is structural baseline only — not a quality claim.
 */
import type { ComparisonDimension } from "./types.js";

export const COMPARISON_DIMENSIONS: ComparisonDimension[] = [
  {
    id: "schema_compliance",
    label: "Schema compliance",
    score_range: [0, 100],
    evidence_source: "ReasoningResponse.validation_result",
    pass_threshold: 100,
    blocking: true,
    comparison_method: "exact_schema_match",
    notes: "Both providers must satisfy the same expected structured-response schema.",
  },
  {
    id: "objective_fulfilment",
    label: "Objective fulfilment",
    score_range: [0, 100],
    evidence_source: "structured_output vs frozen objective",
    pass_threshold: 80,
    blocking: true,
    comparison_method: "rubric_vs_objective",
    notes: "Same frozen objective; no provider-specific prompt drift.",
  },
  {
    id: "knowledge_usage",
    label: "Knowledge usage",
    score_range: [0, 100],
    evidence_source: "Knowledge Snapshot references cited in response",
    pass_threshold: 70,
    blocking: false,
    comparison_method: "reference_coverage",
    notes: "Prefer responses that stay within frozen Knowledge Snapshot refs.",
  },
  {
    id: "skill_adherence",
    label: "Skill adherence",
    score_range: [0, 100],
    evidence_source: "skill_id + capability in frozen package",
    pass_threshold: 90,
    blocking: true,
    comparison_method: "skill_contract_match",
    notes: "Must use the same Skill request as Mock baseline.",
  },
  {
    id: "designbrief_completeness",
    label: "DesignBrief completeness",
    score_range: [0, 100],
    evidence_source: "DesignBrief contract fields after mapping",
    pass_threshold: 90,
    blocking: true,
    comparison_method: "designbrief_field_coverage",
    notes: "Mapped DesignBrief must satisfy renderer contract version.",
  },
  {
    id: "ats_compliance",
    label: "ATS compliance",
    score_range: [0, 100],
    evidence_source: "Resume Critic ATS score",
    pass_threshold: 95,
    blocking: true,
    comparison_method: "critic_ats_delta",
    notes: "Critic ATS threshold unchanged from Resume Critic gate.",
  },
  {
    id: "visual_quality_proxy",
    label: "Visual-quality proxy",
    score_range: [0, 100],
    evidence_source: "Resume Critic visual score",
    pass_threshold: 85,
    blocking: false,
    comparison_method: "critic_visual_delta",
    notes: "Proxy only — not human visual QA.",
  },
  {
    id: "typography_planning",
    label: "Typography planning",
    score_range: [0, 100],
    evidence_source: "DesignBrief.typography + Critic typography",
    pass_threshold: 85,
    blocking: false,
    comparison_method: "typography_field_compare",
    notes: "Compare planning fields, not rendered pixels.",
  },
  {
    id: "layout_planning",
    label: "Layout planning",
    score_range: [0, 100],
    evidence_source: "DesignBrief.layout + Critic layout",
    pass_threshold: 85,
    blocking: false,
    comparison_method: "layout_field_compare",
    notes: "Single-column ATS layout expectations remain locked.",
  },
  {
    id: "revision_usefulness",
    label: "Revision usefulness",
    score_range: [0, 100],
    evidence_source: "structured revision / feedback fields",
    pass_threshold: 60,
    blocking: false,
    comparison_method: "revision_actionability",
    notes: "Useful when CHANGES_REQUESTED paths are compared later.",
  },
  {
    id: "deterministic_downstream_compatibility",
    label: "Deterministic downstream compatibility",
    score_range: [0, 100],
    evidence_source: "Editor Compatibility + Renderer load",
    pass_threshold: 100,
    blocking: true,
    comparison_method: "editor_compat_pass_fail",
    notes: "Canvas must load in Fabric 6.9.1 without conversion.",
  },
  {
    id: "critic_scores",
    label: "Critic scores",
    score_range: [0, 100],
    evidence_source: "Resume Critic overall / dimension scores",
    pass_threshold: 90,
    blocking: true,
    comparison_method: "score_delta_and_gate",
    notes: "Critic Gate Ready=YES required for founder-facing compare.",
  },
  {
    id: "latency",
    label: "Latency",
    score_range: [0, 100],
    evidence_source: "execution_duration_ms",
    pass_threshold: 50,
    blocking: false,
    comparison_method: "latency_ratio_vs_mock",
    notes: "Informational — Mock latency is not a quality claim.",
  },
  {
    id: "token_usage",
    label: "Token usage",
    score_range: [0, 100],
    evidence_source: "estimated / actual tokens",
    pass_threshold: 50,
    blocking: false,
    comparison_method: "token_ratio_vs_budget",
    notes: "Must respect per-task token limit when configured.",
  },
  {
    id: "estimated_cost",
    label: "Estimated cost",
    score_range: [0, 100],
    evidence_source: "cost estimate vs single-test max",
    pass_threshold: 100,
    blocking: true,
    comparison_method: "cost_within_authorization",
    notes: "Mock cost is always 0; Real must stay under authorization.",
  },
  {
    id: "safety_privacy_compliance",
    label: "Safety and privacy compliance",
    score_range: [0, 100],
    evidence_source: "privacy classification + safety_flags",
    pass_threshold: 100,
    blocking: true,
    comparison_method: "privacy_policy_gate",
    notes: "External routing only when policy permits classification.",
  },
  {
    id: "hallucination_or_unsupported_claims",
    label: "Hallucination or unsupported claims",
    score_range: [0, 100],
    evidence_source: "claims vs Knowledge Snapshot + artifacts",
    pass_threshold: 90,
    blocking: true,
    comparison_method: "unsupported_claim_scan",
    notes: "Flag inventing catalog IDs, credentials, or live publish claims.",
  },
  {
    id: "founder_preference_alignment",
    label: "Founder preference alignment",
    score_range: [0, 100],
    evidence_source: "learning domain + founder Knowledge refs",
    pass_threshold: 70,
    blocking: false,
    comparison_method: "preference_signal_overlap",
    notes: "Soft signal from founder learning / preferences.",
  },
];

export function buildComparisonScorecard() {
  return {
    version: "1.0.0",
    generated_at: new Date().toISOString(),
    mock_is_quality_claim: false,
    mock_role: "structural_baseline_only",
    dimensions: COMPARISON_DIMENSIONS,
    dimension_count: COMPARISON_DIMENSIONS.length,
    blocking_dimensions: COMPARISON_DIMENSIONS.filter((d) => d.blocking).map(
      (d) => d.id,
    ),
  };
}
