/**
 * Generate AI OS restart shell script.
 */
export function generateRestartScript(): string {
  return [
    "#!/usr/bin/env bash",
    "# AI OS Restart Script — generated by Deployment Manager (Agent #106)",
    "set -euo pipefail",
    "",
    'DIR="$(cd "$(dirname "$0")" && pwd)"',
    "",
    'echo "[AI OS] Restart: shutdown → startup"',
    'bash "$DIR/shutdown.sh"',
    'bash "$DIR/startup.sh"',
    'echo "[AI OS] Restart complete."',
    "exit 0",
    "",
  ].join("\n");
}
