/**
 * Generate AI OS shutdown shell script.
 */
import type { DeploymentPlan } from "./types.js";

export function generateShutdownScript(plan: DeploymentPlan): string {
  const lines = [
    "#!/usr/bin/env bash",
    "# AI OS Shutdown Script — generated by Deployment Manager (Agent #106)",
    "# Graceful reverse-order stop markers. No process kill of business services.",
    "set -euo pipefail",
    "",
    'ROOT="$(cd "$(dirname "$0")/../../../.." && pwd)"',
    'cd "$ROOT"',
    'OUT="$ROOT/SOS/07_LOGS/saios/deployment-manager"',
    'mkdir -p "$OUT"',
    "",
    'echo "[AI OS] Shutting down in reverse dependency order..."',
    "",
  ];

  for (const id of plan.shutdown_order) {
    const dept = plan.departments.find((d) => d.id === id);
    if (!dept) continue;
    lines.push(`echo "[AI OS] STOP ${dept.label} (${dept.id})"`);
    lines.push(
      `echo "{\\"id\\":\\"${dept.id}\\",\\"action\\":\\"stop\\",\\"at\\":\\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\\"}" >> "$OUT/shutdown-ledger.jsonl"`,
    );
  }

  lines.push("");
  lines.push(
    'echo "{\\"status\\":\\"STOPPED\\",\\"at\\":\\"$(date -u +%Y-%m-%dT%H:%M:%SZ)\\"}" > "$OUT/runtime-lifecycle.json"',
  );
  lines.push('echo "[AI OS] Shutdown sequence complete."');
  lines.push("exit 0");
  lines.push("");
  return lines.join("\n");
}
