/**
 * Generate AI OS startup shell script.
 */
import type { DeploymentPlan } from "./types.js";

export function generateStartupScript(plan: DeploymentPlan): string {
  const lines = [
    "#!/usr/bin/env bash",
    "# AI OS Startup Script — generated by Deployment Manager (Agent #106)",
    "# Does not provision VPS/Docker. Invokes department verify targets in order.",
    "set -euo pipefail",
    "",
    'ROOT="$(cd "$(dirname "$0")/../../../.." && pwd)"',
    'cd "$ROOT"',
    "",
    'echo "[AI OS] Starting deployment sequence..."',
    `echo "[AI OS] Plan version: ${plan.version}"`,
    `echo "[AI OS] Departments: ${plan.department_count}"`,
    "",
  ];

  for (const id of plan.startup_order) {
    const dept = plan.departments.find((d) => d.id === id);
    if (!dept) continue;
    lines.push(`echo "[AI OS] START ${dept.label} (${dept.id})"`);
    lines.push(`npm run ${dept.verify_command}`);
    lines.push("");
  }

  lines.push('echo "[AI OS] Startup sequence complete."');
  lines.push("exit 0");
  lines.push("");
  return lines.join("\n");
}
