import type { ResumeGeneratorRule } from "./types.js";

/**
 * Resume Generator Rules — DESIGN rules for Resume Workers (#054).
 * These govern visual design decisions, NOT editor/Fabric integration rules.
 * Editor integration rules remain in ResumeGenerationSpecification.ts.
 */
export const RESUME_GENERATOR_RULES: readonly ResumeGeneratorRule[] = [
  // ── Spacing ──
  {
    id: "section-gap-minimum",
    category: "spacing",
    rule: "Never place a section heading closer than 24px below the previous section's last content line",
    min: 24,
    severity: "required",
    applies_to_tiers: ["all"],
    rationale: "Corpus median vertical gap is 24–35px; gaps below 18px reduce scanability",
  },
  {
    id: "section-gap-preferred",
    category: "spacing",
    rule: "Preferred vertical gap between major sections",
    value: 32,
    min: 28,
    max: 48,
    severity: "recommended",
    applies_to_tiers: ["all"],
    rationale: "Operations and executive families average 31–38px section separation",
  },
  {
    id: "heading-to-body-gap",
    category: "spacing",
    rule: "Never place body text closer than 8px below a section heading",
    min: 8,
    severity: "required",
    applies_to_tiers: ["all"],
    rationale: "Headings need breathing room before bullet lists or paragraphs",
  },
  {
    id: "left-gutter-minimum",
    category: "spacing",
    rule: "Never place readable content closer than 40px from the left page edge",
    min: 40,
    severity: "required",
    applies_to_tiers: ["ats_safe"],
    rationale: "LAYOUT_SAFE_AREA and corpus analysis; 40px ≈ 0.5 inch print margin",
  },
  {
    id: "left-gutter-preferred",
    category: "spacing",
    rule: "Preferred left gutter for main content column",
    value: 48,
    min: 40,
    max: 72,
    severity: "recommended",
    applies_to_tiers: ["all"],
    rationale: "Corpus 10th-percentile left position clusters at 40–70px",
  },
  {
    id: "right-margin-minimum",
    category: "spacing",
    rule: "Keep content at least 40px from right page edge",
    min: 40,
    severity: "required",
    applies_to_tiers: ["ats_safe"],
    rationale: "Prevents text clipping on export and print",
  },
  {
    id: "bullet-indent",
    category: "spacing",
    rule: "Indent experience bullets 16–24px from section title left edge",
    min: 16,
    max: 24,
    severity: "recommended",
    applies_to_tiers: ["all"],
    rationale: "Visual hierarchy without breaking ATS linear text flow",
  },
  {
    id: "line-height-body",
    category: "spacing",
    rule: "Body text line height multiplier",
    value: 1.35,
    min: 1.2,
    max: 1.5,
    severity: "recommended",
    applies_to_tiers: ["all"],
    rationale: "Improves readability for dense experience sections",
  },

  // ── Typography ──
  {
    id: "font-family-max",
    category: "typography",
    rule: "Never exceed two font families in a single template",
    max: 2,
    severity: "required",
    applies_to_tiers: ["all"],
    rationale: "18 families observed across corpus; multi-family templates score lower on ATS",
  },
  {
    id: "font-family-ats",
    category: "typography",
    rule: "ATS tier: use only fonts from FONT_TIERS.ats_safe",
    severity: "required",
    applies_to_tiers: ["ats_safe"],
    rationale: "Web fonts must have system fallbacks for ATS export",
  },
  {
    id: "body-size-floor",
    category: "typography",
    rule: "Never set body or bullet text below 10.5pt",
    min: 10.5,
    severity: "required",
    applies_to_tiers: ["all"],
    rationale: "Corpus minimum observed 10.487pt; below 10pt fails validation",
  },
  {
    id: "body-size-preferred",
    category: "typography",
    rule: "Preferred body text size",
    value: 11,
    min: 10.5,
    max: 12,
    severity: "recommended",
    applies_to_tiers: ["all"],
    rationale: "Corpus average ~17pt includes headings; body clusters 10.5–12pt",
  },
  {
    id: "name-headline-size",
    category: "typography",
    rule: "Candidate name headline size",
    min: 24,
    max: 48,
    severity: "recommended",
    applies_to_tiers: ["all"],
    rationale: "Executive/creative families use 28–40pt; academic 24–28pt",
  },
  {
    id: "section-heading-size",
    category: "typography",
    rule: "Section heading size",
    min: 11,
    max: 16,
    severity: "recommended",
    applies_to_tiers: ["all"],
    rationale: "Must be visually distinct from body but not compete with name",
  },
  {
    id: "char-spacing-limit",
    category: "typography",
    rule: "Never exceed charSpacing of 50 on body text",
    max: 50,
    severity: "required",
    applies_to_tiers: ["all"],
    rationale: "Corpus shows charSpacing up to 210 — extreme values harm OCR/ATS",
  },
  {
    id: "uppercase-section-titles",
    category: "typography",
    rule: "Section titles may use uppercase at 11–12pt with +50 to +150 charSpacing",
    severity: "recommended",
    applies_to_tiers: ["visual", "all"],
    rationale: "Common pattern in corporate-sidebar and finance families",
  },

  // ── Color ──
  {
    id: "background-white",
    category: "color",
    rule: "Page background must be #ffffff or within 3% of white",
    severity: "required",
    applies_to_tiers: ["all"],
    rationale: "Export and print assume white paper",
  },
  {
    id: "text-contrast",
    category: "color",
    rule: "Body text fill must be #111827, #1f2937, #374151, or #000000",
    severity: "required",
    applies_to_tiers: ["all"],
    rationale: "WCAG contrast on white background",
  },
  {
    id: "accent-color-count",
    category: "color",
    rule: "Use at most one accent color plus neutrals",
    max: 1,
    severity: "recommended",
    applies_to_tiers: ["all"],
    rationale: "Corpus palettes with 3+ accent fills reduce professional cohesion",
  },
  {
    id: "sidebar-contrast",
    category: "color",
    rule: "Light text on dark sidebar must use #ffffff or #f9fafb",
    severity: "required",
    applies_to_tiers: ["visual"],
    rationale: "Corporate-sidebar family pattern",
  },

  // ── Layout ──
  {
    id: "single-column-ats",
    category: "layout",
    rule: "ATS tier must use single-column content flow",
    severity: "required",
    applies_to_tiers: ["ats_safe"],
    rationale: "Multi-column templates average ATS score 58 vs 88 for executive-ats",
  },
  {
    id: "sidebar-width",
    category: "layout",
    rule: "Accent sidebar width",
    min: 200,
    max: 280,
    severity: "recommended",
    applies_to_tiers: ["visual"],
    rationale: "28–35% of 794px A4 width",
  },
  {
    id: "no-negative-coords",
    category: "layout",
    rule: "Never position content Textbox objects at negative left or top",
    severity: "required",
    applies_to_tiers: ["all"],
    rationale: "92 corpus objects use negative coords — breaks reading order",
  },
  {
    id: "header-band-height",
    category: "layout",
    rule: "Header band (name + contact) should occupy 15–25% of page height",
    min: 168,
    max: 280,
    severity: "recommended",
    applies_to_tiers: ["all"],
    rationale: "Corpus header rects cluster in top 170–250px",
  },
  {
    id: "alignment-grid",
    category: "layout",
    rule: "Snap horizontal positions to 8px or 10px alignment grid",
    value: 10,
    severity: "recommended",
    applies_to_tiers: ["all"],
    rationale: "Corpus left gutters cluster on 10px increments",
  },

  // ── Sections ──
  {
    id: "section-order-default",
    category: "sections",
    rule: "Preferred section order: Contact → Summary → Experience → Education → Skills → Projects → Certifications",
    severity: "recommended",
    applies_to_tiers: ["all"],
    rationale: "Matches CATEGORY_SECTION_DEFAULTS and corpus keyword frequency",
  },
  {
    id: "experience-before-education",
    category: "sections",
    rule: "For candidates with 2+ years experience, place Experience before Education",
    severity: "recommended",
    applies_to_tiers: ["all"],
    rationale: "Standard US/UK recruiter scan pattern",
  },
  {
    id: "education-first-entry",
    category: "sections",
    rule: "Entry-level and academic templates: Education before Experience",
    severity: "recommended",
    applies_to_tiers: ["ats_safe"],
    rationale: "Academic-entry family pattern (t038, t039, t046)",
  },
  {
    id: "section-heading-plain-text",
    category: "sections",
    rule: "Section headings must be plain Textbox objects, never rasterized or icon-font glyphs",
    severity: "required",
    applies_to_tiers: ["all"],
    rationale: "ATS cannot parse icon fonts or images as section titles",
  },

  // ── Decoration ──
  {
    id: "divider-thickness",
    category: "decoration",
    rule: "Horizontal section divider stroke width",
    min: 0.5,
    max: 2,
    severity: "recommended",
    applies_to_tiers: ["all"],
    rationale: "Corpus lines used as dividers; thicker lines add visual weight",
  },
  {
    id: "divider-length",
    category: "decoration",
    rule: "Section dividers should span 60–100% of content column width",
    severity: "recommended",
    applies_to_tiers: ["visual"],
    rationale: "Full-bleed dividers in sidebar layouts stop at main column edge",
  },
  {
    id: "decoration-density-ats",
    category: "decoration",
    rule: "ATS tier decoration-to-textbox ratio must stay below 0.12",
    max: 0.12,
    severity: "required",
    applies_to_tiers: ["ats_safe"],
    rationale: "Minimal-ats and executive-ats families cluster below 0.12",
  },
  {
    id: "decoration-density-visual",
    category: "decoration",
    rule: "Visual tier decoration density may reach 0.35 but not exceed 0.5",
    max: 0.5,
    severity: "recommended",
    applies_to_tiers: ["visual"],
    rationale: "Designer-portfolio peaks above 0.35; higher risks clutter",
  },
  {
    id: "no-icon-font-headings",
    category: "decoration",
    rule: "Never use Material Icons or icon fonts as section headings",
    severity: "forbidden",
    applies_to_tiers: ["all"],
    rationale: "RESUME_GENERATION_SPECIFICATION forbidden list",
  },

  // ── Balance / whitespace ──
  {
    id: "whitespace-ratio-ats",
    category: "balance",
    rule: "ATS tier: maintain 55–75% whitespace ratio on page",
    min: 0.55,
    max: 0.75,
    severity: "recommended",
    applies_to_tiers: ["ats_safe"],
    rationale: "Dense pages score lower on recruiter scan tests",
  },
  {
    id: "whitespace-ratio-visual",
    category: "balance",
    rule: "Visual tier: whitespace ratio 40–65%",
    min: 0.4,
    max: 0.65,
    severity: "recommended",
    applies_to_tiers: ["visual"],
    rationale: "Creative templates trade whitespace for visual elements",
  },
  {
    id: "visual-balance-columns",
    category: "balance",
    rule: "Two-column layouts: sidebar content volume should not exceed 40% of total text area",
    max: 0.4,
    severity: "recommended",
    applies_to_tiers: ["visual"],
    rationale: "Prevents sidebar-heavy layouts that starve main narrative",
  },
  {
    id: "name-contact-balance",
    category: "balance",
    rule: "Name width should not exceed 80% of content column; contact lines below or beside",
    severity: "recommended",
    applies_to_tiers: ["all"],
    rationale: "Prevents orphaned contact info on wrapped lines",
  },

  // ── Widgets / images ──
  {
    id: "no-skill-bars-ats",
    category: "widgets",
    rule: "Never use skill progress bars in ATS tier",
    severity: "forbidden",
    applies_to_tiers: ["ats_safe"],
    rationale: "Grouped widget objects reduce parse reliability",
  },
  {
    id: "no-star-ratings-ats",
    category: "widgets",
    rule: "Never use star rating widgets in ATS tier",
    severity: "forbidden",
    applies_to_tiers: ["ats_safe"],
    rationale: "Observed in t075 healthcare template — ATS risk",
  },
  {
    id: "no-photos-ats-us-uk",
    category: "widgets",
    rule: "Never include headshot images in US/UK ATS tier templates",
    severity: "forbidden",
    applies_to_tiers: ["ats_safe"],
    rationale: "ATS_STANDARDS and market norms",
  },
  {
    id: "profile-image-size",
    category: "widgets",
    rule: "Profile image slot size (visual tier)",
    min: 80,
    max: 150,
    severity: "recommended",
    applies_to_tiers: ["visual"],
    rationale: "IMAGE_FRAME_SIZE default 150px; corpus images cluster 80–140px",
  },
  {
    id: "icon-size",
    category: "widgets",
    rule: "Decorative icon or graphic max dimension",
    max: 32,
    severity: "recommended",
    applies_to_tiers: ["visual"],
    rationale: "Larger graphics compete with text hierarchy",
  },
  {
    id: "group-depth",
    category: "widgets",
    rule: "Never nest Groups deeper than 2 levels",
    max: 2,
    severity: "required",
    applies_to_tiers: ["all"],
    rationale: "151 groups in corpus; deep nesting scrambles export order",
  },
  {
    id: "skills-format-ats",
    category: "widgets",
    rule: "ATS tier skills: comma-separated Textbox or vertical plain list — never tables or bars",
    severity: "required",
    applies_to_tiers: ["ats_safe"],
    rationale: "Tables for skills layout are forbidden in generation spec",
  },
];

export function getGeneratorRulesForTier(tier: "ats_safe" | "visual"): ResumeGeneratorRule[] {
  return RESUME_GENERATOR_RULES.filter(
    (r) => r.applies_to_tiers.includes("all") || r.applies_to_tiers.includes(tier),
  );
}

export function getRequiredGeneratorRules(): ResumeGeneratorRule[] {
  return RESUME_GENERATOR_RULES.filter((r) => r.severity === "required" || r.severity === "forbidden");
}
