/**
 * Initial Skill Library definitions — Agent #117.5
 */
import type { SkillDefinition } from "./Skill.js";

export const INITIAL_SKILLS: readonly SkillDefinition[] = [
  // Resume
  {
    id: "resume.ats_analysis",
    name: "ATS Analysis",
    domain: "resume",
    description: "Analyze ATS compatibility of a resume template candidate",
    capability: "complex_visual_critique",
    quality_tier: "strong",
    privacy_classification: "INTERNAL",
    composes: [],
    inputs: ["template_ref", "sample_content_ref"],
    outputs: ["ats_score", "issues", "recommendations"],
    deterministic: false,
    enabled: true,
  },
  {
    id: "resume.layout_planning",
    name: "Layout Planning",
    domain: "resume",
    description: "Plan resume layout structure and sections",
    capability: "design_planning",
    quality_tier: "strong",
    privacy_classification: "INTERNAL",
    composes: ["common.planning"],
    inputs: ["role_family", "constraints"],
    outputs: ["layout_plan"],
    deterministic: false,
    enabled: true,
  },
  {
    id: "resume.typography_planning",
    name: "Typography Planning",
    domain: "resume",
    description: "Plan type scale, fonts, and hierarchy for resumes",
    capability: "design_planning",
    quality_tier: "strong",
    privacy_classification: "INTERNAL",
    composes: [],
    inputs: ["layout_plan", "brand_constraints"],
    outputs: ["typography_plan"],
    deterministic: false,
    enabled: true,
  },
  {
    id: "resume.visual_hierarchy",
    name: "Visual Hierarchy",
    domain: "resume",
    description: "Evaluate and plan visual hierarchy",
    capability: "complex_visual_critique",
    quality_tier: "strong",
    privacy_classification: "INTERNAL",
    composes: ["resume.typography_planning"],
    inputs: ["layout_plan", "preview_ref"],
    outputs: ["hierarchy_assessment"],
    deterministic: false,
    enabled: true,
  },
  {
    id: "resume.resume_critique",
    name: "Resume Critique",
    domain: "resume",
    description: "Holistic critique of a resume candidate before founder review",
    capability: "complex_visual_critique",
    quality_tier: "strong",
    privacy_classification: "INTERNAL",
    composes: [
      "resume.ats_analysis",
      "resume.visual_hierarchy",
      "common.risk_analysis",
    ],
    inputs: ["template_ref", "qa_report_ref"],
    outputs: ["critique", "approval_prediction"],
    deterministic: false,
    enabled: true,
  },
  {
    id: "resume.founder_feedback_interpretation",
    name: "Founder Feedback Interpretation",
    domain: "resume",
    description: "Interpret structured founder feedback into revision actions",
    capability: "founder_feedback_interpretation",
    quality_tier: "strong",
    privacy_classification: "INTERNAL",
    composes: ["common.revision_planning"],
    inputs: ["feedback", "proposal_ref"],
    outputs: ["interpretation", "revision_actions"],
    deterministic: false,
    enabled: true,
  },
  {
    id: "resume.resume_json_planning",
    name: "Resume JSON Planning",
    domain: "resume",
    description: "Plan Fabric/JSON structure for a template (intelligence assist)",
    capability: "structured_json_generation",
    quality_tier: "economical",
    privacy_classification: "INTERNAL",
    composes: ["resume.layout_planning"],
    inputs: ["layout_plan", "design_dna_ref"],
    outputs: ["json_plan"],
    deterministic: false,
    enabled: true,
  },
  {
    id: "resume.template_naming",
    name: "Template Naming",
    domain: "resume",
    description: "Propose human-readable template names and slugs",
    capability: "structured_json_generation",
    quality_tier: "economical",
    privacy_classification: "INTERNAL",
    composes: [],
    inputs: ["role_family", "style_tags"],
    outputs: ["name", "slug"],
    deterministic: false,
    enabled: true,
  },
  {
    id: "resume.duplicate_detection",
    name: "Duplicate Detection",
    domain: "resume",
    description: "Explain duplicate similarity (deterministic check + optional explanation)",
    capability: "duplicate_explanation",
    quality_tier: "economical",
    privacy_classification: "INTERNAL",
    composes: [],
    inputs: ["candidate_ref", "catalog_refs"],
    outputs: ["is_duplicate", "similarity", "explanation"],
    deterministic: false,
    enabled: true,
  },

  // Website
  {
    id: "website.ux_audit",
    name: "UX Audit",
    domain: "website",
    description: "Audit UX of StudiosisLab surfaces",
    capability: "complex_visual_critique",
    quality_tier: "strong",
    privacy_classification: "INTERNAL",
    composes: ["common.report_generation"],
    inputs: ["route_inventory", "screenshots_ref"],
    outputs: ["ux_findings"],
    deterministic: false,
    enabled: true,
  },
  {
    id: "website.accessibility_audit",
    name: "Accessibility Audit",
    domain: "website",
    description: "Accessibility review of website surfaces",
    capability: "report_summarization",
    quality_tier: "economical",
    privacy_classification: "INTERNAL",
    composes: [],
    inputs: ["route_inventory", "a11y_scan_ref"],
    outputs: ["a11y_findings"],
    deterministic: false,
    enabled: true,
  },
  {
    id: "website.design_critique",
    name: "Design Critique",
    domain: "website",
    description: "Critique website visual design and consistency",
    capability: "complex_visual_critique",
    quality_tier: "strong",
    privacy_classification: "INTERNAL",
    composes: [],
    inputs: ["screenshots_ref", "brand_ref"],
    outputs: ["design_findings"],
    deterministic: false,
    enabled: true,
  },
  {
    id: "website.seo_review",
    name: "SEO Review",
    domain: "website",
    description: "Review SEO metadata and structure",
    capability: "report_summarization",
    quality_tier: "economical",
    privacy_classification: "PUBLIC",
    composes: [],
    inputs: ["sitemap_ref", "page_meta_ref"],
    outputs: ["seo_findings"],
    deterministic: false,
    enabled: true,
  },
  {
    id: "website.competitor_analysis",
    name: "Competitor Analysis",
    domain: "website",
    description: "Analyze competitor product/UX patterns",
    capability: "production_strategy",
    quality_tier: "strong",
    privacy_classification: "PUBLIC",
    composes: ["common.planning"],
    inputs: ["competitor_list", "focus_area"],
    outputs: ["competitor_insights"],
    deterministic: false,
    enabled: true,
  },
  {
    id: "website.performance_review",
    name: "Performance Review",
    domain: "website",
    description: "Interpret performance metrics and propose improvements",
    capability: "log_interpretation",
    quality_tier: "economical",
    privacy_classification: "INTERNAL",
    composes: [],
    inputs: ["lighthouse_ref", "web_vitals_ref"],
    outputs: ["performance_findings"],
    deterministic: false,
    enabled: true,
  },
  {
    id: "website.bug_analysis",
    name: "Bug Analysis",
    domain: "website",
    description: "Diagnose website bugs from reports/logs",
    capability: "failure_diagnosis",
    quality_tier: "strong",
    privacy_classification: "INTERNAL",
    composes: ["common.risk_analysis"],
    inputs: ["bug_report", "log_refs"],
    outputs: ["diagnosis", "suggested_fix"],
    deterministic: false,
    enabled: true,
  },

  // Common
  {
    id: "common.report_generation",
    name: "Report Generation",
    domain: "common",
    description: "Generate structured reports for founder/ops",
    capability: "report_summarization",
    quality_tier: "economical",
    privacy_classification: "INTERNAL",
    composes: ["common.task_summarization"],
    inputs: ["sections", "source_refs"],
    outputs: ["report"],
    deterministic: false,
    enabled: true,
  },
  {
    id: "common.task_summarization",
    name: "Task Summarization",
    domain: "common",
    description: "Summarize task outcomes",
    capability: "status_reporting",
    quality_tier: "economical",
    privacy_classification: "INTERNAL",
    composes: [],
    inputs: ["task_events"],
    outputs: ["summary"],
    deterministic: false,
    enabled: true,
  },
  {
    id: "common.cost_analysis",
    name: "Cost Analysis",
    domain: "common",
    description: "Analyze AI/ops cost (deterministic arithmetic preferred)",
    capability: "cost_arithmetic",
    quality_tier: "deterministic",
    privacy_classification: "INTERNAL",
    composes: [],
    inputs: ["ledger_refs"],
    outputs: ["cost_summary"],
    deterministic: true,
    enabled: true,
  },
  {
    id: "common.risk_analysis",
    name: "Risk Analysis",
    domain: "common",
    description: "Assess operational and quality risks",
    capability: "failure_diagnosis",
    quality_tier: "strong",
    privacy_classification: "INTERNAL",
    composes: [],
    inputs: ["context_refs"],
    outputs: ["risks", "mitigations"],
    deterministic: false,
    enabled: true,
  },
  {
    id: "common.planning",
    name: "Planning",
    domain: "common",
    description: "Generic multi-step planning",
    capability: "production_strategy",
    quality_tier: "strong",
    privacy_classification: "INTERNAL",
    composes: [],
    inputs: ["objective", "constraints"],
    outputs: ["plan"],
    deterministic: false,
    enabled: true,
  },
  {
    id: "common.revision_planning",
    name: "Revision Planning",
    domain: "common",
    description: "Plan revisions from critique or feedback",
    capability: "revision_planning",
    quality_tier: "strong",
    privacy_classification: "INTERNAL",
    composes: ["common.planning"],
    inputs: ["critique_or_feedback"],
    outputs: ["revision_plan"],
    deterministic: false,
    enabled: true,
  },
] as const;
