/**
 * Factory State Reporter — human-readable dashboards.
 */
import type { FactoryProjectState } from "./types.js";

function formatAgent(agent: string): string {
  return agent.startsWith("#") ? agent : `#${agent}`;
}

export function renderProjectStatus(state: FactoryProjectState): string {
  const liveRelease = state.discovery.releases.find((r) => r.status === "released");
  const queue = state.discovery.publication_queue
    .filter((p) => p.state === "ready_to_publish")
    .slice(0, 8);

  return [
    "# Factory Overview",
    "",
    `Generated: ${state.generated_at}`,
    `Factory calibration version: ${state.factory_version}`,
    `Latest agent: ${formatAgent(state.latest_agent)}`,
    `Next agent: ${formatAgent(state.next_agent)}`,
    "",
    "# Current Production",
    "",
    `- Latest batch: **${state.latest_batch}**`,
    `- Latest generation: **${state.latest_generation}**`,
    `- QA status: **${state.qa_status}**`,
    `- Competitive validation: **${state.competitive_validation_status}**`,
    "",
    "# Latest Published Template",
    "",
    liveRelease
      ? `- Catalog: **${liveRelease.catalog_id}**`
      : "- No live release discovered",
    liveRelease ? `- Release ID: **${liveRelease.release_id}**` : "",
    liveRelease ? `- Released: **${liveRelease.release_date}**` : "",
    `- Published templates: ${state.discovery.published_templates.join(", ") || "none"}`,
    "",
    "# Latest Founder Review",
    "",
    `- Latest: **${state.latest_founder_review}**`,
    `- Next: **${state.next_founder_review}**`,
    `- Calibration: **${state.latest_calibration}**`,
    ...state.discovery.founder_reviews.slice(-3).map(
      (fr) => `- ${fr.id}: ${fr.status}${fr.calibration_version ? ` (${fr.calibration_version})` : ""}`,
    ),
    "",
    "# Latest Agent",
    "",
    `- Latest completed: **${formatAgent(state.latest_agent)}**`,
    `- Next available: **${formatAgent(state.next_agent)}**`,
    `- Missing agent numbers: ${
      state.discovery.agents.missing_numbers.length
        ? state.discovery.agents.missing_numbers.map((n) => `#${String(n).padStart(3, "0")}`).join(", ")
        : "none in discovered range"
    }`,
    "",
    "# Current Calibration",
    "",
    `- Version: **${state.latest_calibration}**`,
    `- Visual language: v1.4.1`,
    `- Design DNA calibration: v1.5.0`,
    "",
    "# Current Design DNA",
    "",
    `- Version: **${state.latest_design_dna}**`,
    `- Status: **${state.design_dna_status}**`,
    "",
    "# Current Release",
    "",
    `- Release ID: **${state.latest_release}**`,
    `- Catalog ID: **${state.latest_catalog}**`,
    `- Publication status: **${state.publication_status}**`,
    `- Release manager: **${state.release_manager_status}**`,
    `- Runtime catalog: **${state.runtime_catalog_status}**`,
    "",
    "# Pending Actions",
    "",
    ...state.pending_actions.map((action) => `- ${action}`),
    "",
    "# Publication Queue",
    "",
    ...(queue.length
      ? queue.map(
          (entry) =>
            `- **${entry.catalog_id}** — ${entry.title} (${entry.state}) → ${entry.package_dir ?? "no package"}`,
        )
      : ["- No ready_to_publish packages in catalog queue"]),
    "",
    "# Recent History",
    "",
    ...state.history.map((entry) => `- [${entry.type}] ${entry.summary}`),
    "",
    "# Recommended Next Step",
    "",
    state.publication_status === "published" && state.pending_actions.some((a) => a.includes("ready_to_publish"))
      ? "Review remaining production-batch-001 publication packages for founder approval. Only publish templates with explicit founder final publish approval."
      : state.pending_actions.some((a) => a.includes("founder"))
        ? "Complete pending founder review before additional releases."
        : "Load `SOS/project-state.json` at the start of every mission and include a Factory State Summary before implementation.",
    "",
    "_Auto-generated by Factory State Manager. Do not edit manually._",
  ]
    .filter((line) => line !== "")
    .join("\n");
}

export function renderFactoryStateReport(state: FactoryProjectState): string {
  return [
    "# AGENT #095 — Factory State Manager Report",
    "",
    `**Generated:** ${state.generated_at}`,
    `**Status:** PASS`,
    "",
    "## Discovery Summary",
    "",
    `- Agents discovered: ${state.discovery.agents.records.length}`,
    `- Founder reviews discovered: ${state.discovery.founder_reviews.length}`,
    `- Releases discovered: ${state.discovery.releases.length}`,
    `- Published templates: ${state.discovery.published_templates.length}`,
    `- Publication queue entries: ${state.discovery.publication_queue.length}`,
  "",
    "## Agent Numbering",
    "",
    `- Latest agent: #${state.latest_agent}`,
    `- Next agent: #${state.next_agent}`,
    `- Missing: ${state.discovery.agents.missing_numbers.join(", ") || "none"}`,
    `- Duplicates: ${state.discovery.agents.duplicate_numbers.join(", ") || "none"}`,
    "",
    "## Operational Modules (no agent number in source)",
    "",
    ...state.discovery.operational_modules.map((m) => `- ${m}`),
    "",
    "## Verification Targets",
    "",
    "- numbering continuity",
    "- report consistency",
    "- founder review consistency",
    "- publication consistency",
    "- release consistency",
    "- catalog consistency",
    "- project state consistency",
    "",
    "## Outputs",
    "",
    "- `SOS/project-state.json`",
    "- `SOS/PROJECT_STATUS.md`",
    "- `SOS/09_REPORTS/factory-state-report.md`",
    "",
    "_Orchestration only. No AI systems modified._",
  ].join("\n");
}
